# """add department description

# Revision ID: 48c0240b09b2
# Revises: f080b4f1439a
# Create Date: 2026-03-12 18:34:09.743189

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '48c0240b09b2'
# down_revision: Union[str, Sequence[str], None] = 'f080b4f1439a'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('audit_logs', 'user_id',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=True)
#     op.alter_column('automations', 'created_by',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=True)
#     op.alter_column('decisions', 'outcome_id',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=True)
#     op.alter_column('decisions', 'created_by',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=True)
#     op.add_column('departments', sa.Column('description', sa.Text(), nullable=True))
#     op.alter_column('simulations', 'created_by',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('simulations', 'created_by',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#     op.drop_column('departments', 'description')
#     op.alter_column('decisions', 'created_by',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#     op.alter_column('decisions', 'outcome_id',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#     op.alter_column('automations', 'created_by',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#     op.alter_column('audit_logs', 'user_id',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#     # ### end Alembic commands ###

"""add department description

Revision ID: 48c0240b09b2
Revises: f080b4f1439a
Create Date: 2026-03-12 18:34:09.743189
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = "48c0240b09b2"
down_revision: Union[str, Sequence[str], None] = "f080b4f1439a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "departments",
        sa.Column("description", sa.Text(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_column("departments", "description")