"""Outcomes and signals seeding support

Revision ID: 6f443cd1d1f2
Revises: b6dbe8976741
Create Date: 2026-03-09 11:27:29.100403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f443cd1d1f2'
down_revision: Union[str, Sequence[str], None] = 'b6dbe8976741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
