"""add activity logs table

Revision ID: a84a8e5b5b12
Revises: 67b087ec54b7
Create Date: 2026-03-10 11:02:42.427245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a84a8e5b5b12'
down_revision: Union[str, Sequence[str], None] = '67b087ec54b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('activity_logs', 'result')
    op.drop_column('activity_logs', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('activity_logs', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('activity_logs', 'result_data')
    # ### end Alembic commands ###
